//! Job table typed helpers.

use crate::error::{DbError, Result};
use paavo_proto::{BoardSelector, JobId, JobOutcome, JobSource, JobState, Priority};
use rusqlite::{params, Connection, OptionalExtension, Row};
use std::str::FromStr;

/// Insert payload — everything the caller has at enqueue time.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewJob {
    /// ULID, pre-generated by the caller.
    pub id: JobId,
    /// Scheduler priority.
    pub priority: Priority,
    /// Submitter free text.
    pub submitter: String,
    /// Origin (cli vs scheduler).
    pub source: JobSource,
    /// Selector the scheduler will match against the board fleet.
    pub board_selector: BoardSelector,
    /// Effective inactivity timeout (already resolved against the daemon
    /// default; ELF override is applied later when paavo-probe parses the
    /// ELF section).
    pub inactivity_timeout_ms: u64,
    /// Effective hard-max wall clock for this job.
    pub hard_max_ms: u64,
    /// blake3 of the uploaded tar.
    pub tar_blake3: String,
    /// On-disk location of the persisted tar.
    pub tar_path: String,
    /// Packages to `cargo update -p ...` before building. HTTP-submitted
    /// jobs always pass `vec![]` (dep graph is locked at submit time);
    /// the nightly cron threads each `[[corpus]].cargo_update` here so
    /// soak runs pull fresh embassy revisions (spec §8.1 step 4).
    pub cargo_update_packages: Vec<String>,
    /// `true` when the caller wants to bypass the build cache for this
    /// job — paavod will always invoke `paavo_build::build_release`
    /// rather than reusing a cached ELF for the same `tar_blake3`. Set
    /// from `JobSpec::skip_cache` on the HTTP ingress side (`paavo-cli
    /// run --skip-cache`); always `false` for the nightly cron's
    /// scheduled jobs (the cron benefits from cache hits).
    pub skip_cache: bool,
}

/// Captured terminal-state transition payload.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OutcomeRecord {
    /// Target terminal state (one of `Passed`/`Failed`/`TimedOut`/`Aborted`).
    pub state: JobState,
    /// Fully-tagged outcome.
    pub outcome: JobOutcome,
    /// Wall-clock finish time in epoch ms.
    pub finished_at_ms: i64,
}

/// One row from the `job` table.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct JobRow {
    /// Job id.
    pub id: JobId,
    /// Priority.
    pub priority: Priority,
    /// Submitter text.
    pub submitter: String,
    /// Origin.
    pub source: JobSource,
    /// Selector.
    pub board_selector: BoardSelector,
    /// Effective inactivity timeout (ms).
    pub inactivity_timeout_ms: u64,
    /// Hard-max wall clock (ms).
    pub hard_max_ms: u64,
    /// Current state.
    pub state: JobState,
    /// Decoded `JobOutcome`, when in a terminal state.
    pub outcome: Option<JobOutcome>,
    /// Board id this job was dispatched to.
    pub board_id: Option<String>,
    /// Enqueue time, epoch ms.
    pub submitted_at: i64,
    /// Time the scheduler picked this job, epoch ms.
    pub started_at: Option<i64>,
    /// Time the worker reached terminal state, epoch ms.
    pub finished_at: Option<i64>,
    /// blake3 of the uploaded tar.
    pub tar_blake3: String,
    /// On-disk tar path.
    pub tar_path: String,
    /// ELF path once `paavo-build` finishes, otherwise `None`.
    pub elf_path: Option<String>,
    /// Packages to `cargo update -p ...` before building. Empty for
    /// HTTP-submitted jobs; populated for Scheduled jobs from
    /// `[[corpus]].cargo_update`.
    pub cargo_update_packages: Vec<String>,
    /// `true` when the caller wants to bypass the build cache for
    /// this job — paavod always invokes `paavo_build::build_release`
    /// rather than reusing a cached ELF. Mirrors
    /// `NewJob::skip_cache`. Surfaced on `JobView` for the UI.
    pub skip_cache: bool,
}

impl JobRow {
    /// Insert a new job in `Submitted` state.
    pub fn insert(conn: &Connection, j: &NewJob, now_ms: i64) -> Result<()> {
        let sel_json = serde_json::to_string(&j.board_selector)?;
        let pkgs_json = serde_json::to_string(&j.cargo_update_packages)?;
        conn.execute(
            "INSERT INTO job (
                id, priority, submitter, source, board_selector,
                inactivity_timeout_ms, hard_max_ms, state, outcome_detail,
                board_id, submitted_at, started_at, finished_at,
                tar_blake3, tar_path, elf_path, cargo_update_packages,
                skip_cache
            ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 'submitted', NULL, NULL,
                      ?8, NULL, NULL, ?9, ?10, NULL, ?11, ?12)",
            params![
                j.id.to_string(),
                j.priority.weight() as i64,
                j.submitter,
                source_to_str(j.source),
                sel_json,
                j.inactivity_timeout_ms as i64,
                j.hard_max_ms as i64,
                now_ms,
                j.tar_blake3,
                j.tar_path,
                pkgs_json,
                j.skip_cache as i64,
            ],
        )?;
        Ok(())
    }

    /// Fetch a job by id. Returns `DbError::NotFound` if missing so the
    /// HTTP layer can map straight to 404 without pattern-matching on
    /// `rusqlite::Error::QueryReturnedNoRows`.
    pub fn get(conn: &Connection, id: &JobId) -> Result<Self> {
        match conn.query_row(
            "SELECT * FROM job WHERE id = ?1",
            params![id.to_string()],
            from_row,
        ) {
            Ok(row_result) => row_result,
            Err(rusqlite::Error::QueryReturnedNoRows) => Err(crate::error::DbError::NotFound {
                entity: "job",
                id: id.to_string(),
            }),
            Err(other) => Err(other.into()),
        }
    }

    /// Fetch a job by id, returning `Ok(None)` if missing.
    pub fn find(conn: &Connection, id: &JobId) -> Result<Option<Self>> {
        let row = conn
            .query_row(
                "SELECT * FROM job WHERE id = ?1",
                params![id.to_string()],
                from_row,
            )
            .optional()?;
        match row {
            Some(r) => Ok(Some(r?)),
            None => Ok(None),
        }
    }

    /// Returns up to `limit` jobs in `Submitted` state, in scheduler
    /// dispatch order: **highest priority first** (smaller
    /// `Priority::weight()` value sorts first — i.e. `Interactive` before
    /// `Scheduled`); within a priority cohort, **oldest first**.
    pub fn list_submitted(conn: &Connection, limit: u32) -> Result<Vec<Self>> {
        let mut stmt = conn.prepare(
            "SELECT * FROM job WHERE state = 'submitted'
             ORDER BY priority ASC, submitted_at ASC LIMIT ?1",
        )?;
        let rows = stmt
            .query_map(params![limit as i64], from_row)?
            .collect::<std::result::Result<Vec<_>, _>>()?
            .into_iter()
            .collect::<Result<Vec<_>>>()?;
        Ok(rows)
    }

    /// Returns the `limit` most recently submitted jobs in the given state,
    /// newest first. **For scheduler dispatch order on `Submitted`, use
    /// `list_submitted` instead** — it sorts by priority + age (oldest first
    /// within a priority cohort), not by submission time alone.
    pub fn list_by_state(conn: &Connection, state: JobState, limit: u32) -> Result<Vec<Self>> {
        let mut stmt = conn.prepare(
            "SELECT * FROM job WHERE state = ?1
             ORDER BY submitted_at DESC LIMIT ?2",
        )?;
        let rows = stmt
            .query_map(params![state_to_str(state), limit as i64], from_row)?
            .collect::<std::result::Result<Vec<_>, _>>()?
            .into_iter()
            .collect::<Result<Vec<_>>>()?;
        Ok(rows)
    }

    /// Returns the `limit` most recently submitted jobs across **all
    /// states**, newest first. Powers the web viewer's recent-jobs lists
    /// (dashboard + jobs index), which need a mixed-state feed rather
    /// than the state-filtered slice that `list_by_state` produces.
    ///
    /// Ties on `submitted_at` (same millisecond) are broken by `id DESC`
    /// — ULID ids embed a monotonic millisecond timestamp, so this keeps
    /// the ordering deterministic even when two jobs land in the same
    /// `submitted_at` tick.
    pub fn list_recent(conn: &Connection, limit: u32) -> Result<Vec<Self>> {
        let mut stmt = conn.prepare(
            "SELECT * FROM job
             ORDER BY submitted_at DESC, id DESC LIMIT ?1",
        )?;
        let rows = stmt
            .query_map(params![limit as i64], from_row)?
            .collect::<std::result::Result<Vec<_>, _>>()?
            .into_iter()
            .collect::<Result<Vec<_>>>()?;
        Ok(rows)
    }

    /// `Submitted → Building`, recording the chosen board and start time.
    /// Errors if the job is not in `Submitted` state (0 rows updated).
    pub fn transition_to_building(
        conn: &Connection,
        id: &JobId,
        board_id: &str,
        now_ms: i64,
    ) -> Result<()> {
        // TODO(later): replace DbError::UnknownEnum with a dedicated
        // DbError::StateConflict { id, attempted, actual? } variant. Reusing
        // UnknownEnum is semantically wrong (this is a state-machine violation,
        // not an unknown enum value) but the variant shape carries the data we
        // need without expanding the error API. Applies equally to
        // transition_to_running and finalize below.
        let n = conn.execute(
            "UPDATE job SET state = 'building', board_id = ?1, started_at = ?2
             WHERE id = ?3 AND state = 'submitted'",
            params![board_id, now_ms, id.to_string()],
        )?;
        if n == 0 {
            return Err(DbError::UnknownEnum {
                column: "job.state",
                value: "expected 'submitted' for transition_to_building".into(),
            });
        }
        Ok(())
    }

    /// `Building → Running`, recording the built ELF path.
    /// Errors if the job is not in `Building` state (0 rows updated).
    pub fn transition_to_running(conn: &Connection, id: &JobId, elf_path: &str) -> Result<()> {
        let n = conn.execute(
            "UPDATE job SET state = 'running', elf_path = ?1
             WHERE id = ?2 AND state = 'building'",
            params![elf_path, id.to_string()],
        )?;
        if n == 0 {
            return Err(DbError::UnknownEnum {
                column: "job.state",
                value: "expected 'building' for transition_to_running".into(),
            });
        }
        Ok(())
    }

    /// Apply a terminal-state transition with outcome. Errors if the job
    /// id does not exist, or if the job is already in a terminal state (no
    /// re-finalize).
    ///
    /// Panics if `rec.state.is_terminal()` is false — this is a caller bug,
    /// not a runtime error. The alternative (writing `finished_at` on a
    /// non-terminal row) would corrupt the implicit "finished_at iff
    /// terminal" invariant.
    pub fn finalize(conn: &Connection, id: &JobId, rec: &OutcomeRecord) -> Result<()> {
        assert!(
            rec.state.is_terminal(),
            "finalize requires a terminal state"
        );
        let detail_json = serde_json::to_string(&rec.outcome)?;
        let n = conn.execute(
            "UPDATE job SET state = ?1, outcome_detail = ?2, finished_at = ?3
             WHERE id = ?4 AND state IN ('submitted','building','running')",
            params![
                state_to_str(rec.state),
                detail_json,
                rec.finished_at_ms,
                id.to_string()
            ],
        )?;
        if n == 0 {
            return Err(DbError::UnknownEnum {
                column: "job.state",
                value: "expected non-terminal state (or unknown job id) for finalize".into(),
            });
        }
        Ok(())
    }

    /// Delete a job; `ON DELETE CASCADE` clears its log_frames.
    pub fn delete(conn: &Connection, id: &JobId) -> Result<()> {
        conn.execute("DELETE FROM job WHERE id = ?1", params![id.to_string()])?;
        Ok(())
    }
}

fn priority_from_i64(n: i64) -> Result<Priority> {
    match n {
        0 => Ok(Priority::Interactive),
        1 => Ok(Priority::Scheduled),
        other => Err(DbError::UnknownEnum {
            column: "job.priority",
            value: other.to_string(),
        }),
    }
}

fn source_to_str(s: JobSource) -> &'static str {
    match s {
        JobSource::Cli => "cli",
        JobSource::Scheduler => "scheduler",
    }
}

fn source_from_str(s: &str) -> Result<JobSource> {
    match s {
        "cli" => Ok(JobSource::Cli),
        "scheduler" => Ok(JobSource::Scheduler),
        other => Err(DbError::UnknownEnum {
            column: "job.source",
            value: other.to_string(),
        }),
    }
}

fn state_to_str(s: JobState) -> &'static str {
    match s {
        JobState::Submitted => "submitted",
        JobState::Building => "building",
        JobState::Running => "running",
        JobState::Passed => "passed",
        JobState::Failed => "failed",
        JobState::TimedOut => "timedout",
        JobState::Aborted => "aborted",
    }
}

fn state_from_str(s: &str) -> Result<JobState> {
    Ok(match s {
        "submitted" => JobState::Submitted,
        "building" => JobState::Building,
        "running" => JobState::Running,
        "passed" => JobState::Passed,
        "failed" => JobState::Failed,
        "timedout" => JobState::TimedOut,
        "aborted" => JobState::Aborted,
        other => {
            return Err(DbError::UnknownEnum {
                column: "job.state",
                value: other.to_string(),
            })
        }
    })
}

/// Map a row to a Result, with JSON/enum decoding errors surfacing as
/// `DbError`.
fn from_row(r: &Row<'_>) -> rusqlite::Result<Result<JobRow>> {
    let id_str: String = r.get("id")?;
    let priority_i64: i64 = r.get("priority")?;
    let submitter: String = r.get("submitter")?;
    let source_str: String = r.get("source")?;
    let sel_json: String = r.get("board_selector")?;
    let inactivity_raw: i64 = r.get("inactivity_timeout_ms")?;
    let hardmax_raw: i64 = r.get("hard_max_ms")?;
    let state_str: String = r.get("state")?;
    let outcome_json: Option<String> = r.get("outcome_detail")?;
    let board_id: Option<String> = r.get("board_id")?;
    let submitted_at: i64 = r.get("submitted_at")?;
    let started_at: Option<i64> = r.get("started_at")?;
    let finished_at: Option<i64> = r.get("finished_at")?;
    let tar_blake3: String = r.get("tar_blake3")?;
    let tar_path: String = r.get("tar_path")?;
    let elf_path: Option<String> = r.get("elf_path")?;
    let pkgs_json: String = r.get("cargo_update_packages")?;
    let skip_cache_raw: i64 = r.get("skip_cache")?;

    Ok((|| -> Result<JobRow> {
        let id = JobId::from_str(&id_str).map_err(|_| DbError::UnknownEnum {
            column: "job.id",
            value: id_str.clone(),
        })?;
        let priority = priority_from_i64(priority_i64)?;
        let source = source_from_str(&source_str)?;
        let board_selector: BoardSelector = serde_json::from_str(&sel_json)?;
        let state = state_from_str(&state_str)?;
        let outcome = match outcome_json {
            Some(j) => Some(serde_json::from_str::<JobOutcome>(&j)?),
            None => None,
        };
        let inactivity_timeout_ms: u64 =
            inactivity_raw
                .try_into()
                .map_err(|_| DbError::UnknownEnum {
                    column: "job.inactivity_timeout_ms",
                    value: "negative or > i64::MAX".into(),
                })?;
        let hard_max_ms: u64 = hardmax_raw.try_into().map_err(|_| DbError::UnknownEnum {
            column: "job.hard_max_ms",
            value: "negative or > i64::MAX".into(),
        })?;
        let cargo_update_packages: Vec<String> = serde_json::from_str(&pkgs_json)?;
        // `skip_cache` is stored as INTEGER 0/1 (SQLite has no native
        // bool). Anything outside that range is a schema invariant
        // violation, not user input, so map to UnknownEnum with the
        // raw value for debugging.
        let skip_cache = match skip_cache_raw {
            0 => false,
            1 => true,
            other => {
                return Err(DbError::UnknownEnum {
                    column: "job.skip_cache",
                    value: other.to_string(),
                });
            }
        };
        Ok(JobRow {
            id,
            priority,
            submitter,
            source,
            board_selector,
            inactivity_timeout_ms,
            hard_max_ms,
            state,
            outcome,
            board_id,
            submitted_at,
            started_at,
            finished_at,
            tar_blake3,
            tar_path,
            elf_path,
            cargo_update_packages,
            skip_cache,
        })
    })())
}
