//! Job table typed helpers.

use crate::error::{DbError, Result};
use paavo_proto::{AbortReason, BoardSelector, JobId, JobOutcome, JobSource, JobState, Priority};
use rusqlite::{params, Connection, OptionalExtension, Row};
use std::str::FromStr;

/// Insert payload — everything the caller has at enqueue time.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewJob {
    /// ULID, pre-generated by the caller.
    pub id: JobId,
    /// Scheduler priority.
    pub priority: Priority,
    /// Submitter free text.
    pub submitter: String,
    /// Origin (cli vs scheduler).
    pub source: JobSource,
    /// Selector the scheduler will match against the board fleet.
    pub board_selector: BoardSelector,
    /// Effective inactivity timeout (already resolved against the daemon
    /// default; ELF override is applied later when paavo-probe parses the
    /// ELF section).
    pub inactivity_timeout_ms: u64,
    /// Effective hard-max wall clock for this job.
    pub hard_max_ms: u64,
    /// blake3 of the uploaded tar.
    pub tar_blake3: String,
    /// On-disk location of the persisted tar.
    pub tar_path: String,
    /// Packages to `cargo update -p ...` before building. HTTP-submitted
    /// jobs always pass `vec![]` (dep graph is locked at submit time);
    /// the nightly cron threads each `[[corpus]].cargo_update` here so
    /// soak runs pull fresh embassy revisions (spec §8.1 step 4).
    pub cargo_update_packages: Vec<String>,
    /// `true` when the caller wants to bypass the build cache for this
    /// job — paavod will always invoke `paavo_build::build_release`
    /// rather than reusing a cached ELF for the same `tar_blake3`. Set
    /// from `JobSpec::skip_cache` on the HTTP ingress side (`paavo-cli
    /// run --skip-cache`); always `false` for the nightly cron's
    /// scheduled jobs (the cron benefits from cache hits).
    pub skip_cache: bool,
}

/// Captured terminal-state transition payload.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OutcomeRecord {
    /// Target terminal state (one of `Passed`/`Failed`/`TimedOut`/`Aborted`).
    pub state: JobState,
    /// Fully-tagged outcome.
    pub outcome: JobOutcome,
    /// Wall-clock finish time in epoch ms.
    pub finished_at_ms: i64,
}

/// One row from the `job` table.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct JobRow {
    /// Job id.
    pub id: JobId,
    /// Priority.
    pub priority: Priority,
    /// Submitter text.
    pub submitter: String,
    /// Origin.
    pub source: JobSource,
    /// Selector.
    pub board_selector: BoardSelector,
    /// Effective inactivity timeout (ms).
    pub inactivity_timeout_ms: u64,
    /// Hard-max wall clock (ms).
    pub hard_max_ms: u64,
    /// Current state.
    pub state: JobState,
    /// Decoded `JobOutcome`, when in a terminal state.
    pub outcome: Option<JobOutcome>,
    /// Board id this job was dispatched to.
    pub board_id: Option<String>,
    /// Enqueue time, epoch ms.
    pub submitted_at: i64,
    /// Time the scheduler picked this job, epoch ms.
    pub started_at: Option<i64>,
    /// Time the worker reached terminal state, epoch ms.
    pub finished_at: Option<i64>,
    /// blake3 of the uploaded tar.
    pub tar_blake3: String,
    /// On-disk tar path.
    pub tar_path: String,
    /// ELF path once `paavo-build` finishes, otherwise `None`.
    pub elf_path: Option<String>,
    /// Packages to `cargo update -p ...` before building. Empty for
    /// HTTP-submitted jobs; populated for Scheduled jobs from
    /// `[[corpus]].cargo_update`.
    pub cargo_update_packages: Vec<String>,
    /// `true` when the caller wants to bypass the build cache for
    /// this job — paavod always invokes `paavo_build::build_release`
    /// rather than reusing a cached ELF. Mirrors
    /// `NewJob::skip_cache`. Surfaced on `JobView` for the UI.
    pub skip_cache: bool,
}

impl JobRow {
    /// Insert a new job in `Submitted` state.
    pub fn insert(conn: &Connection, j: &NewJob, now_ms: i64) -> Result<()> {
        let sel_json = serde_json::to_string(&j.board_selector)?;
        let pkgs_json = serde_json::to_string(&j.cargo_update_packages)?;
        conn.execute(
            "INSERT INTO job (
                id, priority, submitter, source, board_selector,
                inactivity_timeout_ms, hard_max_ms, state, outcome_detail,
                board_id, submitted_at, started_at, finished_at,
                tar_blake3, tar_path, elf_path, cargo_update_packages,
                skip_cache
            ) VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, 'submitted', NULL, NULL,
                      ?8, NULL, NULL, ?9, ?10, NULL, ?11, ?12)",
            params![
                j.id.to_string(),
                j.priority.weight() as i64,
                j.submitter,
                source_to_str(j.source),
                sel_json,
                j.inactivity_timeout_ms as i64,
                j.hard_max_ms as i64,
                now_ms,
                j.tar_blake3,
                j.tar_path,
                pkgs_json,
                j.skip_cache as i64,
            ],
        )?;
        Ok(())
    }

    /// Fetch a job by id. Returns `DbError::NotFound` if missing so the
    /// HTTP layer can map straight to 404 without pattern-matching on
    /// `rusqlite::Error::QueryReturnedNoRows`.
    pub fn get(conn: &Connection, id: &JobId) -> Result<Self> {
        match conn.query_row(
            "SELECT * FROM job WHERE id = ?1",
            params![id.to_string()],
            from_row,
        ) {
            Ok(row_result) => row_result,
            Err(rusqlite::Error::QueryReturnedNoRows) => Err(crate::error::DbError::NotFound {
                entity: "job",
                id: id.to_string(),
            }),
            Err(other) => Err(other.into()),
        }
    }

    /// Fetch a job by id, returning `Ok(None)` if missing.
    pub fn find(conn: &Connection, id: &JobId) -> Result<Option<Self>> {
        let row = conn
            .query_row(
                "SELECT * FROM job WHERE id = ?1",
                params![id.to_string()],
                from_row,
            )
            .optional()?;
        match row {
            Some(r) => Ok(Some(r?)),
            None => Ok(None),
        }
    }

    /// Returns up to `limit` jobs in `Submitted` state, in scheduler
    /// dispatch order: **highest priority first** (smaller
    /// `Priority::weight()` value sorts first — i.e. `Interactive` before
    /// `Scheduled`); within a priority cohort, **oldest first**.
    pub fn list_submitted(conn: &Connection, limit: u32) -> Result<Vec<Self>> {
        let mut stmt = conn.prepare(
            "SELECT * FROM job WHERE state = 'submitted'
             ORDER BY priority ASC, submitted_at ASC LIMIT ?1",
        )?;
        let rows = stmt
            .query_map(params![limit as i64], from_row)?
            .collect::<std::result::Result<Vec<_>, _>>()?
            .into_iter()
            .collect::<Result<Vec<_>>>()?;
        Ok(rows)
    }

    /// Returns up to `limit` jobs in `AwaitingBoard` state, in the same
    /// scheduler dispatch order as `list_submitted` (priority then
    /// oldest-first). Used by the run-stage scheduler.
    pub fn list_awaiting_board(conn: &Connection, limit: u32) -> Result<Vec<Self>> {
        let mut stmt = conn.prepare(
            "SELECT * FROM job WHERE state = 'awaiting_board'
             ORDER BY priority ASC, submitted_at ASC LIMIT ?1",
        )?;
        let rows = stmt
            .query_map(params![limit as i64], from_row)?
            .collect::<std::result::Result<Vec<_>, _>>()?
            .into_iter()
            .collect::<Result<Vec<_>>>()?;
        Ok(rows)
    }

    /// Distinct `tar_blake3` values of jobs currently `Building` — the
    /// single-flight set the build scheduler skips so N identical
    /// concurrent submits compile only once.
    pub fn building_tar_blake3s(conn: &Connection) -> Result<Vec<String>> {
        let mut stmt =
            conn.prepare("SELECT DISTINCT tar_blake3 FROM job WHERE state = 'building'")?;
        let rows = stmt
            .query_map([], |r| r.get::<_, String>(0))?
            .collect::<std::result::Result<Vec<_>, _>>()?;
        Ok(rows)
    }

    /// Next `log_frame.seq` for a job — `COALESCE(MAX(seq), -1) + 1`.
    /// Returns 0 when the job has no frames yet. Lets the run stage
    /// continue the seq space after the build-phase frames so live
    /// viewers see one contiguous timeline across the build→run split.
    pub fn next_log_seq(conn: &Connection, id: &JobId) -> Result<u64> {
        let n: i64 = conn.query_row(
            "SELECT COALESCE(MAX(seq), -1) + 1 FROM log_frame WHERE job_id = ?1",
            params![id.to_string()],
            |r| r.get(0),
        )?;
        Ok(n.max(0) as u64)
    }

    /// Returns the `limit` most recently submitted jobs in the given state,
    /// newest first. **For scheduler dispatch order on `Submitted`, use
    /// `list_submitted` instead** — it sorts by priority + age (oldest first
    /// within a priority cohort), not by submission time alone.
    pub fn list_by_state(conn: &Connection, state: JobState, limit: u32) -> Result<Vec<Self>> {
        let mut stmt = conn.prepare(
            "SELECT * FROM job WHERE state = ?1
             ORDER BY submitted_at DESC LIMIT ?2",
        )?;
        let rows = stmt
            .query_map(params![state_to_str(state), limit as i64], from_row)?
            .collect::<std::result::Result<Vec<_>, _>>()?
            .into_iter()
            .collect::<Result<Vec<_>>>()?;
        Ok(rows)
    }

    /// Returns the `limit` most recently submitted jobs across **all
    /// states**, newest first. Powers the web viewer's recent-jobs lists
    /// (dashboard + jobs index), which need a mixed-state feed rather
    /// than the state-filtered slice that `list_by_state` produces.
    ///
    /// Ties on `submitted_at` (same millisecond) are broken by `id DESC`
    /// — ULID ids embed a monotonic millisecond timestamp, so this keeps
    /// the ordering deterministic even when two jobs land in the same
    /// `submitted_at` tick.
    pub fn list_recent(conn: &Connection, limit: u32) -> Result<Vec<Self>> {
        let mut stmt = conn.prepare(
            "SELECT * FROM job
             ORDER BY submitted_at DESC, id DESC LIMIT ?1",
        )?;
        let rows = stmt
            .query_map(params![limit as i64], from_row)?
            .collect::<std::result::Result<Vec<_>, _>>()?
            .into_iter()
            .collect::<Result<Vec<_>>>()?;
        Ok(rows)
    }

    /// One page of fuzzy-search results, ranked by `fuzzy_score`. `q` is
    /// matched as a case-insensitive subsequence over the lowercased
    /// `id + submitter + state + board_id` haystack; ranking uses the same
    /// `SkimMatcherV2` the web UI ran in memory. The `LIKE` pre-filter
    /// decides membership (cheap), so `fuzzy_score` runs only on matched
    /// rows. Returns the lightweight [`paavo_proto::JobListItem`] projection.
    pub fn search_index_page(
        conn: &Connection,
        q: &str,
        offset: u32,
        limit: u32,
    ) -> Result<Vec<paavo_proto::JobListItem>> {
        let needle = q.trim().to_lowercase();
        let pattern = crate::like::subsequence_pattern(&needle);
        let mut stmt = conn.prepare(
            "SELECT id, state, priority, submitter, board_id, submitted_at, \
                    fuzzy_score(lower(id || ' ' || submitter || ' ' || state || ' ' || coalesce(board_id,'')), ?1) AS score \
             FROM job \
             WHERE lower(id || ' ' || submitter || ' ' || state || ' ' || coalesce(board_id,'')) LIKE ?2 ESCAPE '\\' \
             ORDER BY score DESC, submitted_at DESC, id DESC \
             LIMIT ?3 OFFSET ?4",
        )?;
        let rows = stmt
            .query_map(
                params![needle, pattern, limit as i64, offset as i64],
                index_row,
            )?
            .collect::<std::result::Result<Vec<_>, _>>()?
            .into_iter()
            .collect::<Result<Vec<_>>>()?;
        Ok(rows)
    }

    /// Total fuzzy-search matches for `q` (pagination total). Pure `LIKE`
    /// membership — does **not** call `fuzzy_score`.
    pub fn search_count(conn: &Connection, q: &str) -> Result<u64> {
        let needle = q.trim().to_lowercase();
        let pattern = crate::like::subsequence_pattern(&needle);
        let n: i64 = conn.query_row(
            "SELECT COUNT(*) FROM job \
             WHERE lower(id || ' ' || submitter || ' ' || state || ' ' || coalesce(board_id,'')) LIKE ?1 ESCAPE '\\'",
            params![pattern],
            |r| r.get(0),
        )?;
        Ok(n as u64)
    }

    /// One page of the time-ordered jobs list, newest-first
    /// (`submitted_at DESC, id DESC`), optionally pinned to
    /// `submitted_at <= as_of` for stable pagination under live inserts.
    /// Lightweight [`paavo_proto::JobListItem`] projection — the blank-query
    /// counterpart to `search_index_page`.
    pub fn list_index_page(
        conn: &Connection,
        as_of: Option<i64>,
        offset: u32,
        limit: u32,
    ) -> Result<Vec<paavo_proto::JobListItem>> {
        let (sql, bind): (&str, Vec<i64>) = match as_of {
            Some(t) => (
                "SELECT id, state, priority, submitter, board_id, submitted_at FROM job \
                 WHERE submitted_at <= ?1 ORDER BY submitted_at DESC, id DESC LIMIT ?2 OFFSET ?3",
                vec![t, limit as i64, offset as i64],
            ),
            None => (
                "SELECT id, state, priority, submitter, board_id, submitted_at FROM job \
                 ORDER BY submitted_at DESC, id DESC LIMIT ?1 OFFSET ?2",
                vec![limit as i64, offset as i64],
            ),
        };
        let mut stmt = conn.prepare(sql)?;
        let rows = stmt
            .query_map(rusqlite::params_from_iter(bind), index_row)?
            .collect::<std::result::Result<Vec<_>, _>>()?
            .into_iter()
            .collect::<Result<Vec<_>>>()?;
        Ok(rows)
    }

    /// Count of jobs strictly newer than `as_of` (drives the "N new" pill);
    /// 0 when `as_of` is `None`. Index-backed by `idx_job_submitted_at`.
    pub fn count_newer(conn: &Connection, as_of: Option<i64>) -> Result<u64> {
        let n: i64 = match as_of {
            Some(t) => conn.query_row(
                "SELECT COUNT(*) FROM job WHERE submitted_at > ?1",
                params![t],
                |r| r.get(0),
            )?,
            None => 0,
        };
        Ok(n as u64)
    }

    /// A cheap, bounded fingerprint of the job table for the live poller.
    /// `GROUP BY state` yields ≤ 8 rows; folding each
    /// `(state, count, max(submitted_at))` into a hash detects every insert
    /// (a group's count/max moves) and every state transition (counts shift
    /// between groups) without materializing the table. Heuristic: it misses
    /// only offsetting same-tick transitions that leave all tallies
    /// identical, which self-heals next tick. See design doc §3.3.
    pub fn activity_digest(conn: &Connection) -> Result<u64> {
        use std::hash::{Hash, Hasher};
        let mut stmt = conn.prepare(
            "SELECT state, COUNT(*), COALESCE(MAX(submitted_at), 0) \
             FROM job GROUP BY state ORDER BY state",
        )?;
        let rows = stmt
            .query_map([], |r| {
                Ok((
                    r.get::<_, String>(0)?,
                    r.get::<_, i64>(1)?,
                    r.get::<_, i64>(2)?,
                ))
            })?
            .collect::<std::result::Result<Vec<_>, _>>()?;
        let mut h = std::collections::hash_map::DefaultHasher::new();
        rows.len().hash(&mut h);
        for (state, count, max_sub) in &rows {
            state.hash(&mut h);
            count.hash(&mut h);
            max_sub.hash(&mut h);
        }
        Ok(h.finish())
    }

    /// Page of full job rows, newest-first, optionally pinned to
    /// `submitted_at <= as_of` for stable pagination under live inserts.
    ///
    /// The `as_of` pin freezes the result set against the live insert
    /// stream: paavo-web captures `as_of` once (the newest
    /// `submitted_at` at the moment the user opened the list) and threads
    /// it through every page request, so a job submitted mid-scroll
    /// cannot shift rows across page boundaries. `None` means "no pin"
    /// (newest snapshot, used for the very first page). Ordering matches
    /// `list_recent`/`list_index_page`: `submitted_at DESC, id DESC`.
    pub fn list_page(
        conn: &Connection,
        as_of: Option<i64>,
        offset: u32,
        limit: u32,
    ) -> Result<Vec<Self>> {
        let (sql, bind): (&str, Vec<i64>) = match as_of {
            Some(t) => (
                "SELECT * FROM job WHERE submitted_at <= ?1
                 ORDER BY submitted_at DESC, id DESC LIMIT ?2 OFFSET ?3",
                vec![t, limit as i64, offset as i64],
            ),
            None => (
                "SELECT * FROM job
                 ORDER BY submitted_at DESC, id DESC LIMIT ?1 OFFSET ?2",
                vec![limit as i64, offset as i64],
            ),
        };
        let mut stmt = conn.prepare(sql)?;
        let rows = stmt
            .query_map(rusqlite::params_from_iter(bind), from_row)?
            .collect::<std::result::Result<Vec<_>, _>>()?
            .into_iter()
            .collect::<Result<Vec<_>>>()?;
        Ok(rows)
    }

    /// Count of jobs (optionally `submitted_at <= as_of`). Paired with
    /// `list_page` so paavo-web can render the total page count against
    /// the same `as_of` snapshot the page window is pinned to.
    pub fn count(conn: &Connection, as_of: Option<i64>) -> Result<u64> {
        let n: i64 = match as_of {
            Some(t) => conn.query_row(
                "SELECT COUNT(*) FROM job WHERE submitted_at <= ?1",
                params![t],
                |r| r.get(0),
            )?,
            None => conn.query_row("SELECT COUNT(*) FROM job", [], |r| r.get(0))?,
        };
        Ok(n as u64)
    }

    /// Job counts grouped by state, all-time over retained rows. Backed
    /// by `idx_job_state` (SQLite satisfies the GROUP BY from the index).
    /// Unknown state strings surface as `DbError::UnknownEnum`, matching
    /// the `from_row` family. States with no rows stay zero.
    pub fn state_counts(conn: &Connection) -> Result<paavo_proto::JobStateCounts> {
        let mut counts = paavo_proto::JobStateCounts {
            submitted: 0,
            building: 0,
            awaiting_board: 0,
            running: 0,
            passed: 0,
            failed: 0,
            timed_out: 0,
            aborted: 0,
        };
        let mut stmt = conn.prepare("SELECT state, COUNT(*) FROM job GROUP BY state")?;
        let rows = stmt.query_map([], |r| Ok((r.get::<_, String>(0)?, r.get::<_, i64>(1)?)))?;
        for row in rows {
            let (state_str, n) = row?;
            let n = n as u64;
            match state_from_str(&state_str)? {
                JobState::Submitted => counts.submitted = n,
                JobState::Building => counts.building = n,
                JobState::AwaitingBoard => counts.awaiting_board = n,
                JobState::Running => counts.running = n,
                JobState::Passed => counts.passed = n,
                JobState::Failed => counts.failed = n,
                JobState::TimedOut => counts.timed_out = n,
                JobState::Aborted => counts.aborted = n,
            }
        }
        Ok(counts)
    }

    /// `Submitted → Building`, recording the chosen board and start time.
    /// Errors if the job is not in `Submitted` state (0 rows updated).
    pub fn transition_to_building(
        conn: &Connection,
        id: &JobId,
        board_id: &str,
        now_ms: i64,
    ) -> Result<()> {
        // TODO(later): replace DbError::UnknownEnum with a dedicated
        // DbError::StateConflict { id, attempted, actual? } variant. Reusing
        // UnknownEnum is semantically wrong (this is a state-machine violation,
        // not an unknown enum value) but the variant shape carries the data we
        // need without expanding the error API. Applies equally to
        // transition_to_running and finalize below.
        let n = conn.execute(
            "UPDATE job SET state = 'building', board_id = ?1, started_at = ?2
             WHERE id = ?3 AND state = 'submitted'",
            params![board_id, now_ms, id.to_string()],
        )?;
        if n == 0 {
            return Err(DbError::UnknownEnum {
                column: "job.state",
                value: "expected 'submitted' for transition_to_building".into(),
            });
        }
        Ok(())
    }

    /// `Building → Running`, recording the built ELF path.
    /// Errors if the job is not in `Building` state (0 rows updated).
    pub fn transition_to_running(conn: &Connection, id: &JobId, elf_path: &str) -> Result<()> {
        let n = conn.execute(
            "UPDATE job SET state = 'running', elf_path = ?1
             WHERE id = ?2 AND state = 'building'",
            params![elf_path, id.to_string()],
        )?;
        if n == 0 {
            return Err(DbError::UnknownEnum {
                column: "job.state",
                value: "expected 'building' for transition_to_running".into(),
            });
        }
        Ok(())
    }

    /// `Submitted → Building` for the build-pool stage. Unlike the legacy
    /// `transition_to_building`, claims NO board (the build holds no
    /// hardware); only records `started_at`. The board is claimed later
    /// by `transition_awaiting_to_running`.
    pub fn transition_submitted_to_building(
        conn: &Connection,
        id: &JobId,
        now_ms: i64,
    ) -> Result<()> {
        let n = conn.execute(
            "UPDATE job SET state = 'building', started_at = ?1
             WHERE id = ?2 AND state = 'submitted'",
            params![now_ms, id.to_string()],
        )?;
        if n == 0 {
            return Err(DbError::UnknownEnum {
                column: "job.state",
                value: "expected 'submitted' for transition_submitted_to_building".into(),
            });
        }
        Ok(())
    }

    /// `Building → AwaitingBoard`, recording the stable ELF path. The
    /// caller releases the build slot after this returns.
    pub fn transition_building_to_awaiting_board(
        conn: &Connection,
        id: &JobId,
        elf_path: &str,
    ) -> Result<()> {
        let n = conn.execute(
            "UPDATE job SET state = 'awaiting_board', elf_path = ?1
             WHERE id = ?2 AND state = 'building'",
            params![elf_path, id.to_string()],
        )?;
        if n == 0 {
            return Err(DbError::UnknownEnum {
                column: "job.state",
                value: "expected 'building' for transition_building_to_awaiting_board".into(),
            });
        }
        Ok(())
    }

    /// `AwaitingBoard → Running`, claiming `board_id` (the run claim).
    /// `elf_path` was set at the awaiting-board transition.
    pub fn transition_awaiting_to_running(
        conn: &Connection,
        id: &JobId,
        board_id: &str,
    ) -> Result<()> {
        let n = conn.execute(
            "UPDATE job SET state = 'running', board_id = ?1
             WHERE id = ?2 AND state = 'awaiting_board'",
            params![board_id, id.to_string()],
        )?;
        if n == 0 {
            return Err(DbError::UnknownEnum {
                column: "job.state",
                value: "expected 'awaiting_board' for transition_awaiting_to_running".into(),
            });
        }
        Ok(())
    }

    /// Apply a terminal-state transition with outcome. Errors if the job
    /// id does not exist, or if the job is already in a terminal state (no
    /// re-finalize).
    ///
    /// Panics if `rec.state.is_terminal()` is false — this is a caller bug,
    /// not a runtime error. The alternative (writing `finished_at` on a
    /// non-terminal row) would corrupt the implicit "finished_at iff
    /// terminal" invariant.
    pub fn finalize(conn: &Connection, id: &JobId, rec: &OutcomeRecord) -> Result<()> {
        assert!(
            rec.state.is_terminal(),
            "finalize requires a terminal state"
        );
        let detail_json = serde_json::to_string(&rec.outcome)?;
        let n = conn.execute(
            "UPDATE job SET state = ?1, outcome_detail = ?2, finished_at = ?3
             WHERE id = ?4 AND state IN ('submitted','building','awaiting_board','running')",
            params![
                state_to_str(rec.state),
                detail_json,
                rec.finished_at_ms,
                id.to_string()
            ],
        )?;
        if n == 0 {
            return Err(DbError::UnknownEnum {
                column: "job.state",
                value: "expected non-terminal state (or unknown job id) for finalize".into(),
            });
        }
        Ok(())
    }

    /// Terminalize every job still in `building`/`running` as
    /// `Aborted { by: Interrupted }`, appending a forensic `Warn`
    /// log frame to each. Returns the count reconciled.
    ///
    /// Intended to run ONCE at daemon startup, before the dispatch
    /// loop: any in-flight row at that point is provably orphaned (a
    /// fresh process has no worker thread for it; single-writer
    /// assumption, spec §7). The whole sweep runs in one transaction,
    /// so a crash mid-sweep commits nothing and a re-run is clean;
    /// the operation is idempotent (a second call finds nothing and
    /// returns 0).
    pub fn abort_interrupted_jobs(conn: &Connection, now_ms: i64) -> Result<u64> {
        let outcome_json = serde_json::to_string(&JobOutcome::Aborted {
            by: AbortReason::Interrupted,
        })?;
        const MSG: &str = "job interrupted: paavod restarted while this \
             job was in-flight; any output above is partial";

        let tx = conn.unchecked_transaction()?;
        // Snapshot the orphaned rows (id + started_at). Collected into a
        // Vec so the prepared statement is dropped before the writes.
        let orphans: Vec<(String, Option<i64>)> = {
            let mut stmt = tx.prepare(
                "SELECT id, started_at FROM job
                 WHERE state IN ('building','running')",
            )?;
            let rows = stmt
                .query_map([], |r| {
                    Ok((r.get::<_, String>(0)?, r.get::<_, Option<i64>>(1)?))
                })?
                .collect::<std::result::Result<Vec<_>, _>>()?;
            rows
        };

        for (id, started_at) in &orphans {
            // `started_at` is `&Option<i64>`; copy it out (Option<i64>
            // is Copy) so we can `.map` it by value below.
            let started_at = *started_at;
            // Next seq after whatever was captured before the crash.
            let next_seq: i64 = tx.query_row(
                "SELECT COALESCE(MAX(seq), -1) + 1 FROM log_frame
                 WHERE job_id = ?1",
                params![id],
                |r| r.get(0),
            )?;
            // Continue the job's relative timeline from started_at.
            let ts_us: i64 = started_at
                .map(|s| (now_ms - s).max(0).saturating_mul(1000))
                .unwrap_or(0);
            tx.execute(
                "INSERT INTO log_frame
                   (job_id, seq, ts_us, level, target, message)
                 VALUES (?1, ?2, ?3, 'warn', NULL, ?4)",
                params![id, next_seq, ts_us, MSG],
            )?;
            tx.execute(
                "UPDATE job
                 SET state = 'aborted', outcome_detail = ?1, finished_at = ?2
                 WHERE id = ?3",
                params![outcome_json, now_ms, id],
            )?;
        }
        tx.commit()?;
        Ok(orphans.len() as u64)
    }

    /// Delete a job; `ON DELETE CASCADE` clears its log_frames.
    pub fn delete(conn: &Connection, id: &JobId) -> Result<()> {
        conn.execute("DELETE FROM job WHERE id = ?1", params![id.to_string()])?;
        Ok(())
    }
}

fn priority_from_i64(n: i64) -> Result<Priority> {
    match n {
        0 => Ok(Priority::Interactive),
        1 => Ok(Priority::Scheduled),
        other => Err(DbError::UnknownEnum {
            column: "job.priority",
            value: other.to_string(),
        }),
    }
}

fn source_to_str(s: JobSource) -> &'static str {
    match s {
        JobSource::Cli => "cli",
        JobSource::Scheduler => "scheduler",
    }
}

fn source_from_str(s: &str) -> Result<JobSource> {
    match s {
        "cli" => Ok(JobSource::Cli),
        "scheduler" => Ok(JobSource::Scheduler),
        other => Err(DbError::UnknownEnum {
            column: "job.source",
            value: other.to_string(),
        }),
    }
}

fn state_to_str(s: JobState) -> &'static str {
    match s {
        JobState::Submitted => "submitted",
        JobState::Building => "building",
        JobState::Running => "running",
        JobState::AwaitingBoard => "awaiting_board",
        JobState::Passed => "passed",
        JobState::Failed => "failed",
        JobState::TimedOut => "timedout",
        JobState::Aborted => "aborted",
    }
}

fn state_from_str(s: &str) -> Result<JobState> {
    Ok(match s {
        "submitted" => JobState::Submitted,
        "building" => JobState::Building,
        "running" => JobState::Running,
        "awaiting_board" => JobState::AwaitingBoard,
        "passed" => JobState::Passed,
        "failed" => JobState::Failed,
        "timedout" => JobState::TimedOut,
        "aborted" => JobState::Aborted,
        other => {
            return Err(DbError::UnknownEnum {
                column: "job.state",
                value: other.to_string(),
            })
        }
    })
}

/// Map a row from the lightweight index projection (`list_index_page` /
/// `search_index_page`) to a [`paavo_proto::JobListItem`]. Follows the
/// same double-`Result` shape
/// as `from_row` (outer = rusqlite row error, inner = decode error) so
/// the caller can collect both layers in one chain.
fn index_row(r: &Row<'_>) -> rusqlite::Result<Result<paavo_proto::JobListItem>> {
    let id_str: String = r.get("id")?;
    let state_str: String = r.get("state")?;
    let priority_i64: i64 = r.get("priority")?;
    let submitter: String = r.get("submitter")?;
    let board_id: Option<String> = r.get("board_id")?;
    let submitted_at: i64 = r.get("submitted_at")?;
    Ok((|| -> Result<paavo_proto::JobListItem> {
        let id = JobId::from_str(&id_str).map_err(|_| DbError::UnknownEnum {
            column: "job.id",
            value: id_str.clone(),
        })?;
        Ok(paavo_proto::JobListItem {
            id,
            state: state_from_str(&state_str)?,
            priority: priority_from_i64(priority_i64)?,
            submitter,
            board_id,
            submitted_at,
        })
    })())
}

/// Map a row to a Result, with JSON/enum decoding errors surfacing as
/// `DbError`.
fn from_row(r: &Row<'_>) -> rusqlite::Result<Result<JobRow>> {
    let id_str: String = r.get("id")?;
    let priority_i64: i64 = r.get("priority")?;
    let submitter: String = r.get("submitter")?;
    let source_str: String = r.get("source")?;
    let sel_json: String = r.get("board_selector")?;
    let inactivity_raw: i64 = r.get("inactivity_timeout_ms")?;
    let hardmax_raw: i64 = r.get("hard_max_ms")?;
    let state_str: String = r.get("state")?;
    let outcome_json: Option<String> = r.get("outcome_detail")?;
    let board_id: Option<String> = r.get("board_id")?;
    let submitted_at: i64 = r.get("submitted_at")?;
    let started_at: Option<i64> = r.get("started_at")?;
    let finished_at: Option<i64> = r.get("finished_at")?;
    let tar_blake3: String = r.get("tar_blake3")?;
    let tar_path: String = r.get("tar_path")?;
    let elf_path: Option<String> = r.get("elf_path")?;
    let pkgs_json: String = r.get("cargo_update_packages")?;
    let skip_cache_raw: i64 = r.get("skip_cache")?;

    Ok((|| -> Result<JobRow> {
        let id = JobId::from_str(&id_str).map_err(|_| DbError::UnknownEnum {
            column: "job.id",
            value: id_str.clone(),
        })?;
        let priority = priority_from_i64(priority_i64)?;
        let source = source_from_str(&source_str)?;
        let board_selector: BoardSelector = serde_json::from_str(&sel_json)?;
        let state = state_from_str(&state_str)?;
        let outcome = match outcome_json {
            Some(j) => Some(serde_json::from_str::<JobOutcome>(&j)?),
            None => None,
        };
        let inactivity_timeout_ms: u64 =
            inactivity_raw
                .try_into()
                .map_err(|_| DbError::UnknownEnum {
                    column: "job.inactivity_timeout_ms",
                    value: "negative or > i64::MAX".into(),
                })?;
        let hard_max_ms: u64 = hardmax_raw.try_into().map_err(|_| DbError::UnknownEnum {
            column: "job.hard_max_ms",
            value: "negative or > i64::MAX".into(),
        })?;
        let cargo_update_packages: Vec<String> = serde_json::from_str(&pkgs_json)?;
        // `skip_cache` is stored as INTEGER 0/1 (SQLite has no native
        // bool). Anything outside that range is a schema invariant
        // violation, not user input, so map to UnknownEnum with the
        // raw value for debugging.
        let skip_cache = match skip_cache_raw {
            0 => false,
            1 => true,
            other => {
                return Err(DbError::UnknownEnum {
                    column: "job.skip_cache",
                    value: other.to_string(),
                });
            }
        };
        Ok(JobRow {
            id,
            priority,
            submitter,
            source,
            board_selector,
            inactivity_timeout_ms,
            hard_max_ms,
            state,
            outcome,
            board_id,
            submitted_at,
            started_at,
            finished_at,
            tar_blake3,
            tar_path,
            elf_path,
            cargo_update_packages,
            skip_cache,
        })
    })())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::Db;
    use tempfile::{tempdir, TempDir};

    /// Open a fresh migrated temp DB (registers `fuzzy_score`).
    fn test_db() -> (TempDir, Db) {
        let dir = tempdir().unwrap();
        let db = Db::open(dir.path().join("t.sqlite")).unwrap();
        (dir, db)
    }

    fn new_job(submitter: &str) -> NewJob {
        NewJob {
            id: JobId::new(),
            priority: Priority::Interactive,
            submitter: submitter.into(),
            source: JobSource::Cli,
            board_selector: BoardSelector {
                kind: "mcxa266".into(),
                instance: None,
                wiring_profile: None,
            },
            inactivity_timeout_ms: 120_000,
            hard_max_ms: 900_000,
            tar_blake3: "deadbeef".into(),
            tar_path: "/tmp/x.tar".into(),
            cargo_update_packages: vec![],
            skip_cache: false,
        }
    }

    /// Insert a job; when `board` is `Some`, transition it to `building` so
    /// the board id lands in the searchable haystack. Returns the job id.
    fn insert_job(
        conn: &Connection,
        submitter: &str,
        board: Option<&str>,
        submitted_at: i64,
    ) -> JobId {
        let j = new_job(submitter);
        let id = j.id;
        JobRow::insert(conn, &j, submitted_at).unwrap();
        if let Some(b) = board {
            ensure_board(conn, b);
            JobRow::transition_to_building(conn, &id, b, submitted_at).unwrap();
        }
        id
    }

    /// Seed board `id` (idempotent) so the `job.board_id` FK is satisfied
    /// before `transition_to_building`. `job.board_id REFERENCES board(id)`
    /// and foreign keys are ON.
    fn ensure_board(conn: &Connection, id: &str) {
        use crate::BoardRow;
        use paavo_proto::{BoardHealth, BoardSpec, ProbeSelector};
        if BoardRow::find(conn, id).unwrap().is_some() {
            return;
        }
        let spec = BoardSpec {
            id: id.into(),
            kind: "mcxa266".into(),
            probe_selector: ProbeSelector {
                vid: "1366".into(),
                pid: "1015".into(),
                serial: id.into(),
                interface: None,
            },
            chip_name: "MCXA266VFL".into(),
            target_name: "frdm-mcx-a266".into(),
            wiring_profile: Some("default".into()),
            health: BoardHealth::Healthy,
        };
        BoardRow::insert(conn, &spec, 0).unwrap();
    }

    #[test]
    fn fuzzy_search_isolates_by_submitter() {
        // q="alice": bob/carol lack a,l,i,c,e in order (ULIDs exclude i,l).
        let (_d, db) = test_db();
        let c = db.raw_conn();
        insert_job(c, "alice", None, 3_000);
        insert_job(c, "bob", None, 2_000);
        insert_job(c, "carol", None, 1_000);

        assert_eq!(JobRow::search_count(c, "alice").unwrap(), 1);
        let rows = JobRow::search_index_page(c, "alice", 0, 50).unwrap();
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0].submitter, "alice");
    }

    #[test]
    fn fuzzy_search_cross_field_subsequence_ranks_best_first() {
        // "almcx" spans submitter+board; "alice" (al contiguous) + mcxa
        // ranks above "carol" (a..l split) + mcxa.
        let (_d, db) = test_db();
        let c = db.raw_conn();
        insert_job(c, "alice", Some("mcxa266-01"), 3_000);
        insert_job(c, "carol", Some("mcxa266-03"), 1_000);

        let rows = JobRow::search_index_page(c, "almcx", 0, 50).unwrap();
        assert!(rows.iter().any(|r| r.submitter == "alice"));
        assert_eq!(rows[0].submitter, "alice", "best fuzzy match ranks first");
    }

    #[test]
    fn list_index_page_orders_and_pins() {
        let (_d, db) = test_db();
        let c = db.raw_conn();
        insert_job(c, "alice", None, 3_000);
        insert_job(c, "bob", None, 2_000);
        insert_job(c, "carol", None, 1_000);

        let all = JobRow::list_index_page(c, None, 0, 50).unwrap();
        assert_eq!(
            all.iter().map(|r| r.submitter.as_str()).collect::<Vec<_>>(),
            ["alice", "bob", "carol"]
        );
        let pinned = JobRow::list_index_page(c, Some(2_000), 0, 50).unwrap();
        assert_eq!(
            pinned
                .iter()
                .map(|r| r.submitter.as_str())
                .collect::<Vec<_>>(),
            ["bob", "carol"]
        );
        let p2 = JobRow::list_index_page(c, None, 2, 2).unwrap();
        assert_eq!(p2.len(), 1);
        assert_eq!(p2[0].submitter, "carol");
    }

    #[test]
    fn count_newer_is_strictly_greater() {
        let (_d, db) = test_db();
        let c = db.raw_conn();
        insert_job(c, "alice", None, 3_000);
        insert_job(c, "bob", None, 2_000);
        assert_eq!(JobRow::count_newer(c, None).unwrap(), 0);
        assert_eq!(JobRow::count_newer(c, Some(3_000)).unwrap(), 0, "exclusive");
        assert_eq!(JobRow::count_newer(c, Some(2_000)).unwrap(), 1);
        assert_eq!(JobRow::count_newer(c, Some(0)).unwrap(), 2);
    }

    #[test]
    fn activity_digest_changes_on_insert_and_transition() {
        let (_d, db) = test_db();
        let c = db.raw_conn();
        let empty = JobRow::activity_digest(c).unwrap();
        let id = insert_job(c, "alice", None, 1_000);
        let after_insert = JobRow::activity_digest(c).unwrap();
        assert_ne!(empty, after_insert, "insert must change the digest");
        assert_eq!(
            after_insert,
            JobRow::activity_digest(c).unwrap(),
            "stable no-op"
        );
        ensure_board(c, "mcxa266-01");
        JobRow::transition_to_building(c, &id, "mcxa266-01", 2_000).unwrap();
        let after_transition = JobRow::activity_digest(c).unwrap();
        assert_ne!(
            after_insert, after_transition,
            "transition must change the digest"
        );
    }

    #[test]
    fn like_membership_matches_fuzzy_score_some() {
        let (_d, db) = test_db();
        let c = db.raw_conn();
        insert_job(c, "alice", Some("mcxa266-01"), 5_000);
        insert_job(c, "bob", Some("mcxa266-02"), 4_000);
        insert_job(c, "carol", Some("mcxa266-03"), 3_000);
        insert_job(c, "dave", None, 2_000);
        insert_job(c, "almcx-bot", None, 1_000);

        for needle in ["almcx", "alice", "mcx", "bob", "zzz", "266", ""] {
            // LIKE-membership count (what search_count uses).
            let like_n = JobRow::search_count(c, needle).unwrap();
            // fuzzy_score-Some count over the SAME lowercased haystack.
            let lowered = needle.trim().to_lowercase();
            let udf_n: i64 = c
                .query_row(
                    "SELECT COUNT(*) FROM job WHERE fuzzy_score(\
                     lower(id || ' ' || submitter || ' ' || state || ' ' || coalesce(board_id,'')), ?1) IS NOT NULL",
                    params![lowered],
                    |r| r.get(0),
                )
                .unwrap();
            assert_eq!(
                like_n, udf_n as u64,
                "LIKE-membership and fuzzy_score-Some disagree for needle {needle:?}"
            );
        }
    }

    #[test]
    fn search_index_page_paginates() {
        let (_d, db) = test_db();
        let c = db.raw_conn();
        for (s, t) in [
            ("mcxone", 4_000),
            ("mcxtwo", 3_000),
            ("mcxthree", 2_000),
            ("mcxfour", 1_000),
        ] {
            insert_job(c, s, None, t);
        }
        assert_eq!(JobRow::search_count(c, "mcx").unwrap(), 4);
        let p1 = JobRow::search_index_page(c, "mcx", 0, 2).unwrap();
        let p2 = JobRow::search_index_page(c, "mcx", 2, 2).unwrap();
        assert_eq!(p1.len(), 2);
        assert_eq!(p2.len(), 2);
        // Pages are disjoint (no id in both).
        for a in &p1 {
            assert!(!p2.iter().any(|b| b.id == a.id), "search pages overlap");
        }
        // Offset past the end yields an empty page.
        assert!(JobRow::search_index_page(c, "mcx", 4, 2)
            .unwrap()
            .is_empty());
    }
}
