[build]
target = "thumbv8m.main-none-eabihf"

[target.thumbv8m.main-none-eabihf]
rustflags = [
  "-C", "link-arg=-Tlink.x",       # cortex-m-rt's main linker script
  "-C", "link-arg=-Tdefmt.x",      # defmt's relocation section
]

# Cargo's libgit2 backend on Windows can fail to clone public Github
# repos when the user has a git credential-helper configured (it tries
# to auth even though the repo is anonymous-accessible, then errors out
# instead of falling through to anonymous). Telling cargo to shell out
# to `git` for fetches sidesteps the issue and works the same on Linux.
# See https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
[net]
git-fetch-with-cli = true
